---
all:
  vars:
    ansible_ssh_user: ubuntu
    become: true

  hosts:
    master-1:
      ansible_host: 89.169.152.97
    worker-1:
      ansible_host: 89.169.150.227
    worker-2:
      ansible_host: 89.169.166.52
    worker-3:
      ansible_host: 51.250.40.137
  children:
    kube_control_plane:
      hosts:
        master-1:
    kube_node:
      hosts:
        worker-1:
        worker-2:
        worker-3:
    etcd:
      hosts:
        master-1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
