---
- name: Clone Kubespray
  hosts: localhost
  become: false
  gather_facts: false
  tasks:
  - name: Clone kubespay
      git:
        repo: https://github.com/kubernetes-sigs/kubespray.git
        dest: ~/kubespray

- name: Prepare to install k8s
  ansible.builtin.import_playbook: prepare.yml
 
- name: Install K8S
  ansible.builtin.import_playbook: kubespray/cluster.yml

- name: Copy config k8s
  ansible.builtin.import_playbook: finish-k8s.yml

- name: Install grafana
  ansible.builtin.import_playbook: monitoring.yml
