- name: Install monitoring stack
  hosts: kube_control_plane
  become: false
  gather_facts: false

  tasks:

    - name: Clone kube-prometheus
      git:
        repo: https://github.com/prometheus-operator/kube-prometheus.git
        dest: kube-prometheus

    - name: Create the namespace and CRDs
      ansible.builtin.command:
        cmd: 'kubectl apply --server-side -f manifests/setup'
        chdir: 'kube-prometheus/'

    - name: Wait for namespace to be available
      ansible.builtin.command:
        cmd: 'kubectl wait --for condition=Established --all CustomResourceDefinition --namespace=monitoring'
        chdir: 'kube-prometheus/'

    - name: Deployment kube-prometheus
      ansible.builtin.command:
        cmd: 'kubectl apply -f manifests/'
        chdir: 'kube-prometheus/'
   
    - name: Copy service grafana
      ansible.builtin.copy:
        src: '../k8s/service-grafana.yml'
        dest: '~/'
        mode: '0644'

    - name: Apply service grafana
      ansible.builtin.command:
        cmd: 'kubectl apply -f ~/service-grafana.yml -n monitoring'
    
    - name: Copy network policy
      ansible.builtin.copy:
        src: '../k8s/network-policy.yml'
        dest: '~/'
    
    - name: Apply network policy for grafana
      ansible.builtin.command:
        cmd: 'kubectl apply -f ~/network-policy.yml -n monitoring'
