---
- name: Prepare to install K8S
  hosts: all
  become: true
  gather_facts: false

  pre_tasks:
    - name: Wait for connection
      ansible.builtin.wait_for_connection:
        timeout: 300

  tasks:
     - name: Packages-update
       ansible.builtin.apt:
         name:
           - python3-pip
         update_cache: true

- name: Prepare to install K8S
  hosts: localhost
  become: false
  gather_facts: false

  tasks:
    
    - name: Install requirements
      pip:
        requirements: ~/kubespray/requirements.txt
        
