---
- name: Prepare to install K8S
  hosts: all
  become: true
  gather_facts: false

  pre_tasks:
    - name: Wait for connection
      ansible.builtin.wait_for_connection:
        timeout: 300

  tasks:
     - name: Packages-update
       ansible.builtin.apt:
         name:
           - python3-pip
           
         state: present
         update_cache: true
         
#     - name: Install requirements
#       pip:
#         requirements: https://github.com/kubernetes-sigs/kubespray/blob/master/requirements.txt
         

