name: Transfer Secret

on:
  workflow_dispatch:

jobs:
  transfer-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v2
        with:
          repository: LexionN/devops-diplom-app
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Set secret in target repo
        run: |
          SECRET_VALUE="TEST"
          echo "${{ env.SECRET_VALUE }}" | gh secret set MY_REGISTRY_ID --repo LexionN/devops-diplom-app
