name: Transfer Secrets

on:
  workflow_dispatch:

jobs:
  transfer:
    runs-on: ubuntu-latest
    steps:
      - name: Install GitHub CLI
        run: |
          sudo apt-get install gh

      - name: Login to GitHub
        env:
          PAT: ${{ secrets.PERSONAL_ACCESS_TOKEN }}  # Ваш токен доступа
        run: |
          echo "$PAT" | gh auth login --with-token

      - name: Set secret in another repository
        run: |
          SECRET_VALUE="TEST"
          gh secret set MY_REGISTRY_ID --body $env.SECRET_VALUE --repo LexionN/devops-diplom-app
