name: Terraform CI/CD

on:
  push:
    branches:
      - main
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets. AWS_SECRET_ACCESS_KEY}}
  TF_VAR_access_key: ${{ secrets.TF_VAR_access_key }}
  TF_VAR_secret_key: ${{ secrets.TF_VAR_secret_key }}
  TF_VAR_account_id: ${{ secrets.TF_VAR_account_id }}
  TF_VAR_cloud_id: ${{ secrets.cloud_id }}
  TF_VAR_folder_id: ${{ secrets.folder_id }}
  TF_VAR_default_zone: ${{ secrets.default_zone }}

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Create service account key file
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SA_IAM_KEY }}" | base64 --decode > ~/.ssh/sa-iam.json

    - name: Terraform Init
      run: terraform -chdir=terraform init

    - name: Terraform Validate
      run: terraform -chdir=terraform validate

    - name: Terraform Plan
      id: plan
      run: |
        terraform -chdir=terraform plan -out=tfplan
        echo "tfplan=$(base64 tfplan)" >> $GITHUB_ENV
    
    - name: Terraform Apply
      run: terraform -chdir=terraform apply -auto-approve
